### ISSUE TITLE
ros2: recording doesn't create metadata.yaml

### ISSUE THREAD

**Issue by emersonknapp** [ros-visualization/rqt_bag#127]
`rqt_bag` recordings leave the bag without `metadata.yaml` file, which makes it unusable by some tooling and requires a `ros2 bag reindex`

**Comment by Andre-ex9** [comment]
I'm facing the same issue. Is this a bug or is it the way rqt_bag is intended to work ?

**Comment by emersonknapp** [comment]
This is a bug - I think that the recorder/writer isn't being deconstructed properly so it doesn't create the file.

**Comment by Yadunund** [comment]
Managed to save the metadata.yaml file when closing the plugin with this PR https://github.com/ros-visualization/rqt_bag/pull/141
After closing rqt_bag, I was able to `ros2 bag play BAG` and echo the topics in another terminal.

The "Save bag" button is still disabled. Looking into that next.

**Comment by Yadunund** [comment]
Will keep this open until https://github.com/ros-visualization/rqt_bag/pull/141 is merged

**Comment by clalancette** [comment]
We merged in #141 ages ago, so closing this out.
