### ISSUE TITLE
rqt_bag has no vertical scroll bar until window is resized

### ISSUE THREAD

**Issue by jaredkhan** [ros-visualization/rqt_bag#31]
I am on Ubuntu 16.04 and running rqt_bag with a large bag. The list of topics is taller than the window so a vertical scroll bar is very helpful. This scrollbar only shows up if I resize the window after loading.

![image](https://user-images.githubusercontent.com/3105017/48412672-42878880-e73d-11e8-91d4-97ac518f135f.png)

**Comment by kmhallen** [comment]
Confirmed in Ubuntu 18.04 ROS Melodic too

**Comment by ElonKou** [comment]
I have the same questioon.
Have you solved it yet?

**Comment by erichahn** [comment]
Bump. Still a present issue.

**Comment by marko-curlin** [comment]
I have this issue on Ubuntu 20.04 ROS Noetic. I open a bag with a big number of topics, and only after resizing or moving the window does the scroll bar appear in its place.
