### ISSUE TITLE
Re-release?

### ISSUE THREAD

**Issue by awesomebytes** [ros-visualization/rqt_bag#59]
Hello, I've been hit by the bug fixed in https://github.com/ros-visualization/rqt_bag/pull/54 would it be possible to get a new release please (in my case for Melodic at least)?

Thank you very much!

**Comment by JStech** [comment]
+1 from me. Just ran into it again myself.

**Comment by mjeronimo** [comment]
Released for Melodic and Noetic.

**Comment by mjeronimo** [comment]
Released for Melodic and Noetic.
