### ISSUE TITLE
Timeline not displayed due to no '_mergesort' function

### ISSUE THREAD

**Issue by ktkt2020** [ros-visualization/rqt_bag#90]
It seems the `_mergesort` function in the `rosbag.bag` was replaced by `heapq.merge` (https://github.com/ros/ros_comm/pull/2017).
But in the current version https://github.com/ros-visualization/rqt_bag/blob/b36db71b0af957853a113b9336f5929a5c4d7fc3/rqt_bag/src/rqt_bag/bag_timeline.py#L273
and
https://github.com/ros-visualization/rqt_bag/blob/b36db71b0af957853a113b9336f5929a5c4d7fc3/rqt_bag/src/rqt_bag/bag_timeline.py#L303
the old function was still called.
This might cause the timeline to show incorrectly.

**Comment by zgxsin** [comment]
I am facing the same issue here.

**Comment by BurryChen** [comment]
I have the same issue.

**Comment by ktkt2020** [comment]
Adding the original `_mergesort` function back to `rosbag/bag.py` could temporarily help to show the Timeline (root permission required for the apt-installed ROS). Perhaps an adaptation of `heapq.merge` might be required for ROS1's `rqt_bag`.

https://github.com/ros/ros_comm/blob/47ad91df5cf0a60f29140be21e78b1587d0adf98/tools/rosbag/src/rosbag/bag.py#L2906:L2968

**Comment by MichaelGrupp** [comment]
I created a pull request with a fix: #93
